### ISSUE TITLE
Model.prototype.save() no longer accepts a callback

### ISSUE THREAD

**Issue by Able1991** [dsanel/mongoose-delete#153]
```
MongooseError: Model.prototype.save() no longer accepts a callback"
    at model.save (/Users/User/Workspace/app/node_modules/mongoose/lib/model.js:517:11)"
    at model.schema.methods.delete (/Users/User/Workspace/app/node_modules/mongoose-delete/index.js:248:25)"
    at /Users/User/Workspace/app/node_modules/kareem/index.js:387:18"
    at /Users/User/Workspace/app/node_modules/kareem/index.js:51:7"
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by newbies779** [comment]
I face the same problem, but only with schema.pre('delete', xxxx)

**Comment by tomLadder** [comment]
Having the same issue

**Comment by Able1991** [comment]
I temporarily solved the problem with another plugin
```
export default function mongooseDeleteFix(schema, options) {
  schema.methods.restore = async function (callback) {
    this.deleted = false;
    this.deletedAt = undefined;
    this.deletedBy = undefined;

    if (options.validateBeforeRestore === false) {
      try {
        await this.save({ validateBeforeSave: false });
      } catch (err) {
        return callback(err);
      }

      return this;
    }

    try {
      await this.save();
    } catch (err) {
      return callback(err);
    }

    return this;
  };

  schema.methods.delete = async function (deletedBy, cb) {
    if (typeof deletedBy === "function") {
      cb = deletedBy;
      deletedBy = null;
    }

    this.deleted = true;

    if (schema.path("deletedAt")) {
      this.deletedAt = new Date();
    }

    if (schema.path("deletedBy")) {
      this.deletedBy = deletedBy;
    }

    if (options.validateBeforeDelete === false) {
      try {
        await this.save({ validateBeforeSave: false });
      } catch (err) {
        return cb(err);
      }

      return this;
    }

    try {
      await this.save();
    } catch (err) {
      return cb(err);
    }

    return this;
  };
}
```
