### ISSUE TITLE
Error: schema.options.typeKey

### ISSUE THREAD

**Issue by Stiv1100001** [dsanel/mongoose-delete#63]
Hi, I got this error while launching the server, right after it charges the moongose scheme: 

``` javascript
TypeError: Cannot read property 'typeKey' of undefined
    at module.exports (/home/stefano/fulcrongrv-stable/node_modules/mongoose-delete/index.js:83:34)
    at Object.<anonymous> (/home/stefano/fulcrongrv-stable/src/db/db.schema.js:82:19)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/stefano/fulcrongrv-stable/routes/sinfonia-dei-sette.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/stefano/fulcrongrv-stable/app.js:12:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fulcron@0.1.5 start: 'node ./bin/www'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fulcron@0.1.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stefano/.npm/_logs/2019-08-17T11_59_18_759Z-debug.log
```

The error occurs only when I add the plugin, what could it be?

**Comment by dsanel** [comment]
I try to reproduce this, no error on my side. @Stiv1100001 if you still see this problem, please add a little more info about the environment and we will try to solve it.
